[package]
name = "pi-rs"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
description = "A library for finding your L1/L2/L3 cache sizes "
repository = "https://github.com/bemeurer/pi"
readme = "./README.md"
keywords = ["prime", "counting", "riemann", "analytic", "function"]
categories = ["algorithms", "science"]
license = "BSD-3-Clause"

[badges]
travis-ci = { repository = "bemeurer/pi-rs", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]


[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
overflow-checks = false

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
overflow-checks = false
